{ pkgs, ... }:

# Supervise libinput-gestures (3/4-finger trackpad swipes: workspace switching,
# notification-panel open/close).
#
# Previously enabled via a one-off `systemctl --user enable`, which writes an
# absolute-path symlink into ~/.config/systemd/user pointing at the package's
# current /nix/store path. A later rebuild that changed that store path (even
# via an unrelated input bump) left the symlink dangling and the service
# permanently dead with no visible error outside the journal — observed broken
# since 2026-09-05, unnoticed until swipe gestures and the Super+\ notification
# bind stopped working. Declaring it here instead means the enable-symlink is
# regenerated by every activation, so it can't go stale.
#
# `After`/`WantedBy` target default.target, not graphical-session.target: the
# latter is never started on this Hyprland setup (see
# modules/hypr-session-autosave.nix and modules/hypr-monitor-watch.nix).
{
  systemd.user.services.libinput-gestures = {
    description = "Actions gestures on your touchpad using libinput";
    after = [ "default.target" ];
    wantedBy = [ "default.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.libinput-gestures}/bin/libinput-gestures";
      Environment = "PATH=/run/current-system/sw/bin:/etc/profiles/per-user/%u/bin";
      Restart = "on-failure";
      RestartSec = "5s";
    };
  };
}
